import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // SVG placeholders are generated by our own /api/placeholder route (see
    // src/components/media/property-image.tsx) — never a user-uploaded SVG.
    dangerouslyAllowSVG: true,
    contentDispositionType: "inline",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
};

export default nextConfig;
